# Practical_6: Numpy

In [3]:
import numpy as up

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.


In [2]:
B = up.arange(1,11)
print(B)

[ 1  2  3  4  5  6  7  8  9 10]


---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.



In [17]:
a = up.zeros((3,3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [18]:
a.dtype

dtype('int64')

In [19]:
a = up.zeros((3,3), dtype=up.int16)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [20]:
a.dtype

dtype('int16')

---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.


In [8]:
a1 = up.linspace(0,5,10)
print(a1)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [21]:
a1 = up.linspace(0,5,10, endpoint=False)
print(a1)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.


In [11]:
I = up.eye(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.



In [15]:
print(up.random.random((4,4)))

[[0.78515388 0.47921035 0.2416247  0.08124342]
 [0.78436128 0.96009223 0.56952092 0.72328024]
 [0.016273   0.1237066  0.62311353 0.70500967]
 [0.23191004 0.98613009 0.20808333 0.5952999 ]]


In [23]:
print(up.random.rand(4,4))

[[0.42650861 0.68555876 0.86887409 0.0126237 ]
 [0.01357461 0.58129986 0.16442672 0.34413608]
 [0.40715294 0.43779439 0.50894269 0.23294776]
 [0.75484484 0.25575759 0.81581132 0.19830303]]


In [24]:
up.random.seed(10)

In [25]:
print(up.random.rand(4,4))

[[0.77132064 0.02075195 0.63364823 0.74880388]
 [0.49850701 0.22479665 0.19806286 0.76053071]
 [0.16911084 0.08833981 0.68535982 0.95339335]
 [0.00394827 0.51219226 0.81262096 0.61252607]]


In [26]:
up.random.seed(0)

In [27]:
print(up.random.rand(4,4))

[[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293 ]]


---

### Exercise 6:
Find the shape of a NumPy array.


In [28]:
print(I.shape)

(5, 5)


---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

In [29]:
A = up.arange(16)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [30]:
print(A.reshape(4,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


---

### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```

In [31]:
A.dtype

dtype('int64')

---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

In [32]:
U =[ x for x in up.arange(1,101) if x%2 ==0]
print(U)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [37]:
B = up.linspace(2,100,50,dtype=int)
print(B)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

In [47]:
A = up.random.randint(10, 50, (6,6))
print(A)

[[48 21 28 37 10 24]
 [45 22 30 21 14 16]
 [14 13 22 46 24 25]
 [30 45 33 25 23 31]
 [15 45 10 41 15 40]
 [10 46 44 39 13 44]]


---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

In [42]:
B1 = up.array([[1,2], [2,4]])
print(B1)

[[1 2]
 [2 4]]


In [45]:
A1 = A[1:3, 2:4]
print(A1)

[[29 29]
 [19 42]]


---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

In [46]:
s = A1.sum()
print(s)

119


---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

In [52]:
m = A.mean()
#me = A.median(A)
sd = A.std()
print(f"Mean: {m}")
print("============================")
#Print(f"Median: {me}")
print("============================")
print(f"Standard deviation: {sd}")

Mean: 28.02777777777778
Standard deviation: 12.388359480467297


---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14
```

In [54]:
print(A.min())
print(A.max())

10
48


---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

In [59]:
C = up.random.randint(10,201, (20))
print(C)

[ 60 165  24  51  68  46  20  96  53 114  21  12  61  90  42 192 138  48
  29 184]


In [63]:
ma = up.where(C == C.max())
print(ma)

(array([15]),)


In [64]:
print(f"The maximum value is {C.max()} on position {up.argmax(C)}")

The maximum value is 192 on position 15


---

### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

In [67]:
A2 = up.arange(30)

print(A2[::-1])

[29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6
  5  4  3  2  1  0]


---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17
```

In [73]:
X = up.arange(1, 10).reshape((3, 3))
Y = up.arange(9, 18).reshape((3, 3))
print(X)
print(Y)
print(up.multiply(X,Y))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[  9  20  33]
 [ 48  65  84]
 [105 128 153]]


---

### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

In [75]:
D = up.diag([1,2,3,4])
print(D)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
```

In [80]:
C2 = up.arange(4, 8).reshape((2,2))
C1 = up.arange(9, 13).reshape((2,2))
print(C1)
print(C2)
print(up.multiply(C1,C2))

[[ 9 10]
 [11 12]]
[[4 5]
 [6 7]]
[[36 50]
 [66 84]]


---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python
# Exercise 20
```

In [83]:
print(C2.flatten())
print("========================")
print(C2.ravel())
print("========================")
print(C2.reshape(1,4))
print("========================")

[4 5 6 7]
[4 5 6 7]
[[4 5 6 7]]


---

### Exercise 21:
Stack two NumPy arrays vertically.

```python
# Exercise 21
```

In [86]:
print(up.vstack(C1))
up.vstack

[[ 9 10]
 [11 12]]


In [4]:
ar1 = up.array([1, 2, 3])
ar2 = up.array([4, 5, 6])
st_v = up.vstack((ar1, ar2))
print(st_v)

[[1 2 3]
 [4 5 6]]


---

### Exercise 22:
Stack two NumPy arrays horizontally.

```python
# Exercise 22
```

In [7]:
ar1 = up.array([1, 2, 3])
ar2 = up.array([4, 5, 6])
st_h = up.hstack((ar1, ar2))
print("The stacked horizontally:",st_h)

The stacked horizontally: [1 2 3 4 5 6]


---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python
# Exercise 23
```

In [9]:
arr = up.array([1, 2, 3, 4, 5, 6])

sub_arrs = up.array_split(arr, 3)

print("Multiple sub arrays:")
for sub in sub_arrs:
    print(sub)

Multiple sub arrays:
[1 2]
[3 4]
[5 6]


---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python
# Exercise 24
```

In [11]:
rarr = up.random.rand(4, 4)
rd_arr = up.round(rarr, 2)
print(rd_arr)

[[0.89 0.67 0.49 0.14]
 [0.09 0.62 0.72 0.89]
 [0.09 0.77 0.18 0.5 ]
 [0.96 0.8  0.74 0.75]]


---

### Exercise 25:
Find the unique elements of a NumPy array.

```python
# Exercise 25
```

In [15]:
# Array with duplicate elements
ar = up.array([1, 2, 2, 3, 4, 4, 5])
unel = up.unique(ar)
print(f"Unique elements: {unel}")

Unique elements: [1 2 3 4 5]


---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
# Exercise 26
```

In [16]:
a1 = up.array([1, 4, 9, 3, 11])

# Replacing all elements less than 4 with the value 100
mod_a1 = up.where(a1 < 4, 100, a1)
print("Modified array:", mod_a1)

Modified array: [100   4   9 100  11]


---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27
```

In [18]:
cumulative_sum = up.cumsum(a1)
print("Cumulative sum:", cumulative_sum)

Cumulative sum: [ 1  5 14 17 28]


---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28
```

In [20]:
B3 = up.array([1, 0, 2, 0, 3])
nz = up.count_nonzero(B3)
print("Number of non-zero elements:", nz)

Number of non-zero elements: 3


In [21]:
count = 0
cnt = sum(count+1 for B3 in B3 if B3 != 0)
print(f"Number of non-zero elements: {cnt}")

Number of non-zero elements: 3


---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29
```

In [23]:
rint = up.random.randint(1, 100, size=10)
s_arr = up.sort(rint)
print(f"Sorted array: {s_arr}")

Sorted array: [ 6  7 21 39 55 73 73 76 92 95]


---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30
```

In [25]:
M = up.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

row_sum = up.sum(M, axis=1)
column_sum =up.sum(M, axis=0)
print(f"Row-wise sum: {row_sum}")
print(f"Column-wise sum: {column_sum}")

Row-wise sum: [ 6 15 24]
Column-wise sum: [12 15 18]


---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

In [28]:
D2 = up.random.rand(2, 2)
# Normalize the array 
m = up.min(D2)
M = up.max(D2)
nor_arr = (D2 - m) / (M - m)

print("unchanged array:")
print(D2)
print("Normalized array:")
print(nor_arr)

unchanged array:
[[0.01634247 0.78332395]
 [0.99356714 0.21255491]]
Normalized array:
[[0.         0.78485686]
 [1.         0.20078539]]


---

### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

In [31]:
# Create two arrays
u1 = up.array([-2, 2, 7])
u2 = up.array([0, -5, 4])
dotp = up.dot(u1, u2)
print("Dot product: {}".format(dotp))

Dot product: 18


---

### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

In [36]:
B3 = up.arange(3,12).reshape(3,3)
B3_trace = up.trace(B3)
print("Trace of the matrix:", B3_trace)

Trace of the matrix: 21


---

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

In [40]:
mx = up.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Swap row 0 with row 2
mx[[0, 2]] = mx[[2, 0]]
print("Matrix after swapping rows:")
print(mx)

Matrix after swapping rows:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

In [41]:
B4 = up.array([1, 2, 3, 4])
column_vector = B4[:, up.newaxis]
print("Column vector:")
print(column_vector)

Column vector:
[[1]
 [2]
 [3]
 [4]]


---

### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

In [44]:
B5 = up.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
det = up.linalg.det(B5)
print(f"Determinant of the matrix: {int(det)}")

Determinant of the matrix: 0


---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

In [56]:
B6 = up.array([[3, 1, 2], [5, 2, 0], [1, 3, 8]])
eva, eve = up.linalg.eig(B6)
print("Eigenvalues:", up.round(eva, 3))
print("Eigenvectors:",up.round(eve, 3))

Eigenvalues: [1.86 2.   9.14]
Eigenvectors: [[ 0.025 -0.     0.335]
 [-0.9   -0.894  0.235]
 [ 0.436  0.447  0.912]]


---

### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

In [58]:
A = up.array([[2, 1], [1, 3]])
B = up.array([8, 18])
X = up.linalg.solve(A, B)
print(f"Solution to the system of equations: {X}")

Solution to the system of equations: [1.2 5.6]


---

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

In [61]:
B7 = up.array([10, 20, 30, 40])
b7 = up.random.normal(0, 1, B7.shape) # Generate Gaussian noise
# Add noise to the array
b71 = B7 + b7

# Print the result
print(f"Array with Gaussian noise: {b71}")

Array with Gaussian noise: [11.24063299 19.28716346 30.41403185 40.59420291]


---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

In [66]:
matrix = up.arange(1,17).reshape(4,4)
diagonal = up.diag(matrix)
print(f"Diagonal elements: {diagonal}")

Diagonal elements: [ 1  6 11 16]


---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

In [72]:
B8 = up.random.randint(1,180, (100))
clipped = up.clip(B8, 10, 50)
print(f"The clipped values: {clipped}")

The clipped values: [50 50 50 50 50 50 50 10 50 50 50 50 50 41 50 50 29 29 50 50 50 50 50 50
 50 50 50 50 50 50 50 50 50 17 38 50 50 39 23 50 10 12 50 32 23 50 50 50
 37 50 50 36 50 50 50 50 43 17 10 50 50 41 50 41 50 50 50 50 50 29 50 50
 50 50 50 50 50 50 10 50 50 50 50 50 50 50 50 50 50 50 50 19 48 50 50 33
 32 50 26 50]


---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

In [75]:
B9 = up.array([[1, -2, 3], [-4, 5, -6]])
B9[B9 < 0] = 0
print(B9)

[[1 0 3]
 [0 5 0]]


---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

In [79]:
u = up.array([-1, 3, 5])
v = up.array([4, 2, 1])
innerp = up.inner(u, v)
outerp = up.outer(u, v)
print("Inner product:", innerp)
print("Outer product:")
print(outerp)

Inner product: 7
Outer product:
[[-4 -2 -1]
 [12  6  3]
 [20 10  5]]


---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

In [84]:
from scipy.spatial import distance

points = up.array([[0, 0], [1, 1], [2, 2]])
dists = distance.pdist(points)
print(dists)

[1.41421356 2.82842712 1.41421356]
